import { useMemo, useState } from "react";
import { useMockState } from "~/mocks/store/mock-store";
import { useCurrentUser } from "~/shared/auth/use-current-user";
import { EmptyState } from "~/shared/components/empty-state";
import { StatusChip } from "~/shared/components/status-chip";

export function Page() {
  const state = useMockState(); const user = useCurrentUser(); const [notice, setNotice] = useState("");
  if (!user || user.roleId !== "pengelola" || user.institutionCodes.length !== 1) return <EmptyState title="Halaman ini hanya untuk Pengelola Pesantren" />;
  const reports = state.reports.filter((x) => x.institutionCode === user.institutionCodes[0] && x.validationStatus === "Diterima" && !x.archivedAt); const recommendations = state.recommendations.filter((x) => reports.some((r) => r.id === x.reportId)); const progress = useMemo(() => recommendations.length ? Math.round(recommendations.reduce((n, x) => n + x.progress, 0) / recommendations.length) : 0, [recommendations]); const dimensions = state.instrumentVersions.find((x) => x.id === state.activeInstrumentVersionId)?.dimensions ?? [];
  const download = (kind: string) => setNotice(`Simulasi unduh ${kind}: dokumen dummy tidak dibuat pada prototipe ini.`);
  return <section className="flex flex-col gap-4"><header><p className="kicker">Ringkasan pengelola</p><h1 className="text-2xl font-extrabold text-heading">Laporan pesantren</h1><p className="mt-1 text-sm text-secondary-text">Periode Sep 2026 · {state.instrumentVersions.find((x) => x.id === state.activeInstrumentVersionId)?.label} · dibuat {new Date().toLocaleDateString("id-ID")} oleh {user.name}</p></header><div className="grid gap-3 sm:grid-cols-3"><Metric label="Laporan diterima" value={reports.length} /><Metric label="Completed" value={reports.filter((x) => x.handlingStatus === "Completed").length} /><Metric label="Progres tindak lanjut" value={`${progress}%`} /></div><div className="flex flex-wrap gap-2"><button className="secondary-button" onClick={() => download("PDF")}>Unduh PDF dummy</button><button className="secondary-button" onClick={() => download("Excel")}>Unduh Excel dummy</button></div>{notice && <p role="status" className="rounded border border-line-soft p-3 text-sm">{notice}</p>}<section className="surface p-4"><h2 className="font-bold">Dimensi instrumen</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{dimensions.map((x) => <div key={x.id} className="rounded border border-line-soft p-3 text-sm"><strong>{x.name}</strong><p className="text-secondary-text">{x.indicators.length} indikator · ilustrasi</p></div>)}</div></section><section className="surface p-4"><h2 className="font-bold">Status tindak lanjut</h2><div className="mt-3 divide-y divide-line">{recommendations.map((x) => <div key={x.id} className="flex flex-wrap items-center gap-2 py-3"><strong className="mr-auto">{x.title}</strong><span className="text-sm text-secondary-text">{x.progress}%</span><StatusChip value={x.status} /><StatusChip value={x.priority} /></div>)}</div></section><section className="surface p-4"><h2 className="font-bold">Riwayat laporan</h2><div className="mt-3 divide-y divide-line">{reports.map((x) => <div key={x.id} className="flex flex-wrap gap-2 py-3 text-sm"><strong className="mr-auto">{x.id} · {x.title}</strong><StatusChip value={x.handlingStatus} /><span className="text-secondary-text">{new Date(x.createdAt).toLocaleDateString("id-ID")}</span></div>)}</div></section></section>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="surface p-4"><p className="text-sm text-secondary-text">{label}</p><strong className="text-3xl text-heading">{value}</strong></div>; }
