import { useMemo, useState } from "react";
import { storeActions, useMockState } from "~/mocks/store/mock-store";
import type { Recommendation } from "~/mocks/types";
import { useCurrentUser } from "~/shared/auth/use-current-user";
import { selectRecommendationsForManager } from "~/mocks/store/selectors";
import { EmptyState } from "~/shared/components/empty-state";
import { StatusChip } from "~/shared/components/status-chip";

export function Page() {
  const state = useMockState(); const user = useCurrentUser(); const [status, setStatus] = useState("Semua"); const [priority, setPriority] = useState("Semua"); const [query, setQuery] = useState("");
  if (!user || user.roleId !== "pengelola" || user.institutionCodes.length !== 1) return <EmptyState title="Halaman ini hanya untuk Pengelola Pesantren" />;
  const items = useMemo(() => selectRecommendationsForManager(state, user.institutionCodes[0]).filter((x) => status === "Semua" || x.status === status).filter((x) => priority === "Semua" || x.priority === priority).filter((x) => `${x.title} ${x.location}`.toLowerCase().includes(query.toLowerCase())), [state, user, status, priority, query]);
  return <section className="flex flex-col gap-4"><header><p className="kicker">Penanganan</p><h1 className="text-2xl font-extrabold text-heading">Tindak lanjut</h1><p className="mt-1 text-sm text-secondary-text">Rencana tindakan mengubah laporan menjadi Proses; seluruh rekomendasi terverifikasi menutupnya sebagai Completed.</p></header><div className="surface grid gap-3 p-3 md:grid-cols-3"><select className="min-h-11 rounded border border-line-soft px-3" value={status} onChange={(e) => setStatus(e.target.value)}><option>Semua</option><option>Belum ditindaklanjuti</option><option>Berjalan</option><option>Menunggu verifikasi</option><option>Terverifikasi</option></select><select className="min-h-11 rounded border border-line-soft px-3" value={priority} onChange={(e) => setPriority(e.target.value)}><option>Semua</option><option>Tinggi</option><option>Sedang</option><option>Rendah</option></select><input className="min-h-11 rounded border border-line-soft px-3" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari rekomendasi atau lokasi" /></div>{items.length ? <div className="grid gap-3">{items.map((item) => <Card key={item.id} item={item} />)}</div> : <EmptyState title="Tidak ada tindak lanjut yang cocok" />}</section>;
}
function Card({ item }: { item: Recommendation }) {
  const user = useCurrentUser()!; const [pic, setPic] = useState(item.owner); const [due, setDue] = useState(item.dueDate); const [progress, setProgress] = useState(String(item.progress)); const [note, setNote] = useState(item.lastNote ?? ""); const [evidence, setEvidence] = useState(item.completionEvidence ?? ""); const [message, setMessage] = useState("");
  const save = (verify = false) => { const r = storeActions.updateRecommendation(user, item.id, { owner: pic, dueDate: due, progress: Number(progress), note, evidenceName: evidence, verify }); setMessage(r.ok ? "Tindak lanjut tersimpan." : r.error); };
  const locked = item.status === "Menunggu verifikasi" || item.status === "Terverifikasi";
  return <article className="surface p-4"><div className="flex flex-wrap gap-2"><StatusChip value={item.status} /><StatusChip value={item.priority} /></div><h2 className="mt-2 font-bold text-heading">{item.title}</h2><p className="mt-1 text-sm text-secondary-text">{item.location} · {item.action}</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-sm font-bold">PIC<input className="mt-1 min-h-10 w-full rounded border border-line-soft px-3" value={pic} disabled={item.status !== "Belum ditindaklanjuti"} onChange={(e) => setPic(e.target.value)} /></label><label className="text-sm font-bold">Tenggat<input type="date" className="mt-1 min-h-10 w-full rounded border border-line-soft px-3" value={due} disabled={item.status !== "Belum ditindaklanjuti"} onChange={(e) => setDue(e.target.value)} /></label><label className="text-sm font-bold">Progres (%)<input type="number" min="0" max="100" className="mt-1 min-h-10 w-full rounded border border-line-soft px-3" value={progress} disabled={item.status === "Belum ditindaklanjuti" || locked} onChange={(e) => setProgress(e.target.value)} /></label></div>{item.status === "Berjalan" && <label className="mt-3 block text-sm font-bold">Bukti penyelesaian (wajib bila 100%)<input className="mt-1 min-h-10 w-full rounded border border-line-soft px-3" value={evidence} onChange={(e) => setEvidence(e.target.value)} placeholder="contoh: perbaikan.jpg" /></label>}<label className="mt-3 block text-sm font-bold">Catatan<textarea className="mt-1 min-h-20 w-full rounded border border-line-soft p-3 font-normal" value={note} disabled={item.status === "Terverifikasi"} onChange={(e) => setNote(e.target.value)} /></label>{message && <p role="status" className="mt-2 text-sm">{message}</p>}<div className="mt-3">{item.status === "Menunggu verifikasi" ? <button className="primary-button" onClick={() => save(true)}>Verifikasi pengelola</button> : item.status !== "Terverifikasi" ? <button className="primary-button" onClick={() => save()}>{item.status === "Belum ditindaklanjuti" ? "Buat rencana tindakan" : "Perbarui progres"}</button> : <p className="text-sm text-secondary-text">Terverifikasi · bukti: {item.completionEvidence}</p>}</div></article>;
}
