import { useMemo, useState } from "react";
import { useMockState } from "~/mocks/store/mock-store";
import { EmptyState } from "~/shared/components/empty-state";
import { StatusChip } from "~/shared/components/status-chip";

export function Page() {
  const state=useMockState();const[query,setQuery]=useState("");const[institution,setInstitution]=useState("Semua");const rows=useMemo(()=>state.reports.filter(x=>x.channel==="penilaian-mandiri"&&(institution==="Semua"||x.institutionCode===institution)&&`${x.id} ${x.reporterName} ${x.title}`.toLowerCase().includes(query.toLowerCase())),[state.reports,institution,query]);
  return <section className="flex flex-col gap-4"><header><p className="kicker">Dataset</p><h1 className="text-2xl font-extrabold text-heading">Data penelitian</h1><p className="text-sm text-secondary-text">Katalog snapshot penilaian mandiri beserta provenance dan status validasinya.</p></header><div className="flex flex-wrap gap-2"><input aria-label="Cari data" className="min-h-11 min-w-60 flex-1 rounded border border-line-soft px-3" placeholder="Cari ID, pelapor, atau judul…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter pesantren" className="min-h-11 rounded border border-line-soft bg-white px-3" value={institution} onChange={e=>setInstitution(e.target.value)}><option>Semua</option>{state.institutions.map(x=><option value={x.code} key={x.code}>{x.name}</option>)}</select></div>{rows.length?<div className="surface divide-y divide-line">{rows.map(x=>{const snapshot=state.selfAssessmentSnapshots.find(s=>s.reportId===x.id);const inst=state.institutions.find(i=>i.code===x.institutionCode);return <article className="flex flex-wrap items-center gap-3 p-4 text-sm" key={x.id}><div className="mr-auto"><strong className="text-heading">{x.id} · {inst?.name}</strong><p className="text-xs text-secondary-text">{x.reporterName} · {new Date(x.createdAt).toLocaleString("id-ID")}</p><p className="text-xs text-faint">{snapshot?.instrumentVersionId??"Versi tidak tersedia"} · {snapshot?Object.keys(snapshot.answers).length:0} jawaban</p></div><StatusChip value={x.validationStatus}/></article>})}</div>:<EmptyState title="Data tidak ditemukan" description="Sesuaikan pencarian atau filter pesantren."/>}</section>;
}
