import { Building2 } from "lucide-react";
import { Link } from "react-router";
import type { DashboardDistribution, IndexSummary } from "~/mocks/processors/dashboard-aggregate";
import type { Area, InstrumentVersion, Recommendation, RiskFinding, SelfAssessmentSnapshot } from "~/mocks/types";
import { StatusChip } from "~/shared/components/status-chip";

export function ScoreSummary({ summary, snapshots, versions }: { summary: IndexSummary; snapshots: SelfAssessmentSnapshot[]; versions: InstrumentVersion[] }) {
  const expected = new Map(versions.map((version) => [version.id, version.dimensions.flatMap((dimension) => dimension.indicators).length]));
  const answers = snapshots.reduce((total, snapshot) => total + Object.values(snapshot.answers).filter((answer) => answer.value.trim()).length, 0);
  const indicators = snapshots.reduce((total, snapshot) => total + (expected.get(snapshot.instrumentVersionId) ?? 0), 0);
  const percentage = summary.currentIndex === null ? 0 : Math.max(0, Math.min(100, Math.round(summary.currentIndex)));
  return <article className="surface p-4" aria-labelledby="score-title"><div className="flex flex-wrap items-start gap-4"><div className="relative grid size-36 shrink-0 place-items-center rounded-full" style={{ background: `conic-gradient(#9f1239 ${percentage}%, #eef2f6 ${percentage}% 100%)` }}><span className="grid size-24 place-items-center rounded-full bg-white text-center"><span><strong className="block text-3xl text-heading">{summary.currentIndex === null ? "—" : percentage}</strong><span className="text-xs font-bold text-secondary-text">/100 · ilustrasi</span></span></span></div><div className="min-w-0 flex-1"><p className="kicker">Ringkasan kondisi</p><h2 id="score-title" className="text-lg font-extrabold text-heading">Indeks K3L Pesantren</h2><p className="mt-1 text-xs text-secondary-text">Skor dari snapshot penilaian mandiri yang telah diterima.</p><dl className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3"><Metric label="Indikator dinilai" value={indicators} /><Metric label="Jawaban terisi" value={answers} /><Metric label="Dimensi" value={summary.dimensions.length} /></dl></div></div></article>;
}

function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-md bg-strip px-3 py-2"><dt className="text-[10px] font-bold uppercase tracking-wide text-secondary-text">{label}</dt><dd className="mt-0.5 text-xl font-extrabold text-heading">{value}</dd></div>; }

export function AspectAndRecap({ findings, versions, areas, distribution }: { findings: RiskFinding[]; versions: InstrumentVersion[]; areas: Area[]; distribution: DashboardDistribution }) {
  const dimensionsByIndicator = new Map<string, string>();
  // Hubungan indikator → dimensi berasal dari versi instrumen, bukan kata kunci temuan.
  for (const version of versions) for (const dimension of version.dimensions) for (const indicator of dimension.indicators) dimensionsByIndicator.set(indicator.id, dimension.name);
  const byAspect = new Map<string, number>();
  for (const finding of findings) { const label = dimensionsByIndicator.get(finding.indicator) ?? "Belum dipetakan"; byAspect.set(label, (byAspect.get(label) ?? 0) + 1); }
  const aspectItems = [...byAspect.entries()].map(([label, value]) => ({ label, value }));
  const maxAspect = Math.max(...aspectItems.map((item) => item.value), 1);
  const areaName = new Map(areas.map((area) => [area.id, area.name]));
  const byArea = new Map<string, number>();
  for (const finding of findings) { const label = areaName.get(finding.areaId) ?? finding.location; byArea.set(label, (byArea.get(label) ?? 0) + 1); }
  return <section className="grid gap-3 xl:grid-cols-2" aria-label="Rekapitulasi dashboard"><article className="surface p-4"><h2 className="text-sm font-extrabold text-heading">Temuan per aspek</h2><p className="mt-0.5 text-xs text-secondary-text">Berdasarkan relasi indikator yang tersedia; lainnya ditandai netral.</p>{aspectItems.length ? <div className="mt-4 space-y-3">{aspectItems.map((item) => <div key={item.label}><div className="flex justify-between gap-3 text-sm"><span className="font-bold text-heading">{item.label}</span><strong>{item.value}</strong></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-strip"><div className="h-full rounded-full bg-accent" style={{ width: `${item.value / maxAspect * 100}%` }} /></div></div>)}</div> : <Empty text="Belum ada temuan tervalidasi." />}</article><article className="surface overflow-hidden"><div className="p-4"><h2 className="text-sm font-extrabold text-heading">Rekapitulasi lokasi & risiko</h2><p className="mt-0.5 text-xs text-secondary-text">Setiap angka memakai temuan yang sama dengan distribusi risiko.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[420px] text-left text-sm"><thead className="bg-strip text-xs text-secondary-text"><tr><th className="px-4 py-2">Lokasi</th><th className="px-4 py-2 text-right">Temuan</th><th className="px-4 py-2">Status</th></tr></thead><tbody className="divide-y divide-line">{[...byArea.entries()].map(([name, total]) => <tr key={name}><td className="px-4 py-3 font-semibold text-heading">{name}</td><td className="px-4 py-3 text-right font-extrabold text-heading">{total}</td><td className="px-4 py-3"><span className="text-xs font-semibold text-secondary-text">Temuan tercatat</span></td></tr>)}{!byArea.size ? <tr><td colSpan={3} className="px-4 py-6 text-center text-secondary-text">Belum ada temuan tercatat pada konteks ini.</td></tr> : null}</tbody></table></div><div className="border-t border-line p-4"><ul className="flex flex-wrap gap-3 text-xs font-semibold text-secondary-text">{distribution.risiko.map((item) => <li key={item.label}><StatusChip value={item.label} /> <span className="ml-1">{item.value}</span></li>)}</ul></div></article></section>;
}

function Empty({ text }: { text: string }) { return <p className="mt-4 rounded-md bg-strip p-3 text-sm text-secondary-text">{text}</p>; }

export function FollowUpSummary({ recommendations }: { recommendations: Recommendation[] }) { return <article className="surface overflow-hidden"><div className="flex items-center gap-2 border-b border-line p-4"><Building2 size={17} className="text-primary" aria-hidden /><div><h2 className="text-sm font-extrabold text-heading">Tindak lanjut terbaru</h2><p className="text-xs text-secondary-text">PIC dan status penanganan yang dapat dibaca publik.</p></div><Link to="/tindak-lanjut" className="text-button ms-auto">Lihat semua</Link></div>{recommendations.length ? <ul className="divide-y divide-line">{recommendations.slice(0, 3).map((recommendation) => <li key={recommendation.id} className="flex flex-wrap items-center gap-2 p-4"><div className="min-w-0 flex-1"><p className="text-sm font-bold text-heading">{recommendation.title}</p><p className="mt-0.5 text-xs text-secondary-text">PIC: {recommendation.owner} · progres {recommendation.progress}%</p></div><StatusChip value={recommendation.status} /></li>)}</ul> : <Empty text="Belum ada tindak lanjut publik untuk konteks ini." />}</article>; }
